source 'https://rubygems.org'

gem "builder", "~> 3.2.2"
gem "less", "~> 2.2.2"
gem "middleman", "~> 4.3.7"
gem "middleman-blog", "~> 4.0.0"
gem "middleman-minify-html", "~> 3.3.0"
gem "nokogiri", "~> 1.6.0"
gem "rack-contrib", "~> 1.1.0"
gem "redcarpet", "~> 3.0.0"
gem "therubyracer", "~> 0.12.0"
gem "thin", "~> 1.5.0"

group :development do
  gem "highline", "~> 1.6.15"
end
